### ISSUE TITLE
Conexión con MariaDB

### ISSUE THREAD

**Issue by mansergue** [Proyecto-EGC-G1/AdminCensos-EGC-G1#11]

**Comment by juaguecar** [comment]
[INSTRUCCIONES.pdf](https://github.com/Proyecto-EGC-G1/AdminCensos-EGC-G1/files/1562586/INSTRUCCIONES.pdf)
[configuración de docker en VM con spring (1).pdf](https://github.com/Proyecto-EGC-G1/AdminCensos-EGC-G1/files/1562587/configuracion.de.docker.en.VM.con.spring.1.pdf)

**Comment by juaguecar** [comment]
Documentación de ayuda.
[INSTRUCCIONES.pdf](https://github.com/Proyecto-EGC-G1/AdminCensos-EGC-G1/files/1562589/INSTRUCCIONES.pdf)
[configuración de docker en VM con spring (1).pdf](https://github.com/Proyecto-EGC-G1/AdminCensos-EGC-G1/files/1562590/configuracion.de.docker.en.VM.con.spring.1.pdf)
