### ISSUE TITLE
Hacer modelo Java y repositorios

### ISSUE THREAD

**Issue by mansergue** [Proyecto-EGC-G1/AdminCensos-EGC-G1#6]
Con este modelo: 
https://github.com/Proyecto-EGC-G1/Integracion-EGC-G1/tree/master/Documentación/Sistema_Votaciones/BBDD

Implementar modelo java y repositorios

**Comment by carloztor** [comment]
Implementado modelo java a falta de revisión

**Comment by mansergue** [comment]
Revisado
