### ISSUE TITLE
Proporcionar número de votantes de un censo por votación

### ISSUE THREAD

**Issue by jorgegarciax2** [Proyecto-EGC-G1/AdminCensos-EGC-G1#9]
Desde redes sociales y para ofrecer la funcionalidad de compartir un balance de participación de los votantes en una votación, necesitamos saber si existiría la posibilidad de que nos proporcionaseis el número de votantes de un censo por votación.

El objetivo sería que el equipo de Administración de Censos implementase un método que nos permitiese conocer el número de votantes de un censo por votación.

Desde integración nos han pedido llegar a un acuerdo.

**Comment by mansergue** [comment]
Nos encargamos de actualizar el valor del número de votantes en la base de datos
